language: objective-c
before_install:
  - rvm use ruby-2.0.0-p247
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods
  - cd Example
  - pod install
script: xctool test -workspace SJOManagedObjectController.xcworkspace/ -scheme SJOManagedObjectController -sdk iphonesimulator -arch i386
