language: objective-c
before_install:
  - cd Example
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods
  - pod install
script: xctool test -workspace SJOManagedObjectController.xcworkspace/ -scheme SJOManagedObjectController -sdk iphonesimulator -arch i386
