language: objective-c
before_install:
  - brew update
  - brew install xctool
  - pod install
script: xctool test -workspace SJOManagedObjectController.xcworkspace/ -scheme SJOManagedObjectController
